repos:
  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        args:
          - "--max-line-length=88"
          - "--ignore=E24,E121,E123,E126,E203,E226,E704,E731,W503,W504"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.950"
    hooks:
      - id: mypy
        args: []
        additional_dependencies:
          - "aiohttp==3.8.1"
          - "pydantic==1.9.0"
          - "typer==0.4.1"
  - repo: local
    hooks:
      - id: gradle-test
        name: gradle test
        entry: >
          ./gradlew --info cleanTest test
          --tests StartStopTest
          --tests SingleNodeTest
          --tests ShardingTest
          --tests TwoNodeTest
        language: system
        types_or:
          - python
          - java
        pass_filenames: false
fail_fast: true
